# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Projects/arduino-fpga/fpga/cmod-a7/arduino_cmod-a7.srcs/sources_1/bd/clock_wizard/ip/clock_wizard_clk_wiz_0_0/clock_wizard_clk_wiz_0_0.xci
# IP: The module: 'clock_wizard_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/arduino-fpga/fpga/cmod-a7/arduino_cmod-a7.gen/sources_1/bd/clock_wizard/ip/clock_wizard_clk_wiz_0_0/clock_wizard_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_wizard_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Projects/arduino-fpga/fpga/cmod-a7/arduino_cmod-a7.gen/sources_1/bd/clock_wizard/ip/clock_wizard_clk_wiz_0_0/clock_wizard_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_wizard_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Projects/arduino-fpga/fpga/cmod-a7/arduino_cmod-a7.gen/sources_1/bd/clock_wizard/ip/clock_wizard_clk_wiz_0_0/clock_wizard_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_wizard_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/Projects/arduino-fpga/fpga/cmod-a7/arduino_cmod-a7.srcs/sources_1/bd/clock_wizard/ip/clock_wizard_clk_wiz_0_0/clock_wizard_clk_wiz_0_0.xci
# IP: The module: 'clock_wizard_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/arduino-fpga/fpga/cmod-a7/arduino_cmod-a7.gen/sources_1/bd/clock_wizard/ip/clock_wizard_clk_wiz_0_0/clock_wizard_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_wizard_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Projects/arduino-fpga/fpga/cmod-a7/arduino_cmod-a7.gen/sources_1/bd/clock_wizard/ip/clock_wizard_clk_wiz_0_0/clock_wizard_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_wizard_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Projects/arduino-fpga/fpga/cmod-a7/arduino_cmod-a7.gen/sources_1/bd/clock_wizard/ip/clock_wizard_clk_wiz_0_0/clock_wizard_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_wizard_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
